#############################################################################
# Makefile for building: inews
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ???. 12 23:54:31 2012
# Project:  inews.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile inews.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DDEBUG=1 -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -Iqxmlrpc -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtWebKit -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qxmlrpc/xmlrpc/variant.cpp \
		qxmlrpc/xmlrpc/serverintrospection.cpp \
		qxmlrpc/xmlrpc/server.cpp \
		qxmlrpc/xmlrpc/response.cpp \
		qxmlrpc/xmlrpc/request.cpp \
		qxmlrpc/xmlrpc/client.cpp \
		connector.cpp \
		newsapplication.cpp \
		resourcemanager.cpp \
		feedmodel.cpp \
		textedit.cpp \
		node.cpp \
		file.cpp \
		rssitem.cpp \
		taxonomyterm.cpp \
		centerlawidget.cpp \
		rssviewwidget.cpp \
		nodeeditorwidget.cpp \
		taxonomywidget.cpp \
		rsslistitemdelegate.cpp moc_mainwindow.cpp \
		moc_server_private.cpp \
		moc_server.cpp \
		moc_client.cpp \
		moc_connector.cpp \
		moc_newsapplication.cpp \
		moc_resourcemanager.cpp \
		moc_feedmodel.cpp \
		moc_textedit.cpp \
		moc_centerlawidget.cpp \
		moc_rssviewwidget.cpp \
		moc_nodeeditorwidget.cpp \
		moc_taxonomywidget.cpp \
		qrc_resource.cpp
OBJECTS       = main.o \
		mainwindow.o \
		variant.o \
		serverintrospection.o \
		server.o \
		response.o \
		request.o \
		client.o \
		connector.o \
		newsapplication.o \
		resourcemanager.o \
		feedmodel.o \
		textedit.o \
		node.o \
		file.o \
		rssitem.o \
		taxonomyterm.o \
		centerlawidget.o \
		rssviewwidget.o \
		nodeeditorwidget.o \
		taxonomywidget.o \
		rsslistitemdelegate.o \
		moc_mainwindow.o \
		moc_server_private.o \
		moc_server.o \
		moc_client.o \
		moc_connector.o \
		moc_newsapplication.o \
		moc_resourcemanager.o \
		moc_feedmodel.o \
		moc_textedit.o \
		moc_centerlawidget.o \
		moc_rssviewwidget.o \
		moc_nodeeditorwidget.o \
		moc_taxonomywidget.o \
		qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		inews.pro
QMAKE_TARGET  = inews
DESTDIR       = 
TARGET        = inews

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: inews.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtWebKit.prl \
		/usr/lib/i386-linux-gnu/libQtXml.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile inews.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtWebKit.prl:
/usr/lib/i386-linux-gnu/libQtXml.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile inews.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/inews1.0.0 || $(MKDIR) .tmp/inews1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/inews1.0.0/ && $(COPY_FILE) --parents mainwindow.h qxmlrpc/xmlrpc/variant.h qxmlrpc/xmlrpc/stable.h qxmlrpc/xmlrpc/serverintrospection.h qxmlrpc/xmlrpc/server_private.h qxmlrpc/xmlrpc/server.h qxmlrpc/xmlrpc/response.h qxmlrpc/xmlrpc/request.h qxmlrpc/xmlrpc/client.h connector.h newsapplication.h resourcemanager.h feedmodel.h textedit.h node.h file.h rssitem.h taxonomyterm.h centerlawidget.h rssviewwidget.h nodeeditorwidget.h taxonomywidget.h rsslistitemdelegate.h .tmp/inews1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/inews1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp qxmlrpc/xmlrpc/variant.cpp qxmlrpc/xmlrpc/serverintrospection.cpp qxmlrpc/xmlrpc/server.cpp qxmlrpc/xmlrpc/response.cpp qxmlrpc/xmlrpc/request.cpp qxmlrpc/xmlrpc/client.cpp connector.cpp newsapplication.cpp resourcemanager.cpp feedmodel.cpp textedit.cpp node.cpp file.cpp rssitem.cpp taxonomyterm.cpp centerlawidget.cpp rssviewwidget.cpp nodeeditorwidget.cpp taxonomywidget.cpp rsslistitemdelegate.cpp .tmp/inews1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/inews1.0.0/ && (cd `dirname .tmp/inews1.0.0` && $(TAR) inews1.0.0.tar inews1.0.0 && $(COMPRESS) inews1.0.0.tar) && $(MOVE) `dirname .tmp/inews1.0.0`/inews1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/inews1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_server_private.cpp moc_server.cpp moc_client.cpp moc_connector.cpp moc_newsapplication.cpp moc_resourcemanager.cpp moc_feedmodel.cpp moc_textedit.cpp moc_centerlawidget.cpp moc_rssviewwidget.cpp moc_nodeeditorwidget.cpp moc_taxonomywidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_server_private.cpp moc_server.cpp moc_client.cpp moc_connector.cpp moc_newsapplication.cpp moc_resourcemanager.cpp moc_feedmodel.cpp moc_textedit.cpp moc_centerlawidget.cpp moc_rssviewwidget.cpp moc_nodeeditorwidget.cpp moc_taxonomywidget.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_server_private.cpp: qxmlrpc/xmlrpc/variant.h \
		qxmlrpc/xmlrpc/server_private.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qxmlrpc/xmlrpc/server_private.h -o moc_server_private.cpp

moc_server.cpp: qxmlrpc/xmlrpc/variant.h \
		qxmlrpc/xmlrpc/server.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qxmlrpc/xmlrpc/server.h -o moc_server.cpp

moc_client.cpp: qxmlrpc/xmlrpc/client.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qxmlrpc/xmlrpc/client.h -o moc_client.cpp

moc_connector.cpp: connector.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) connector.h -o moc_connector.cpp

moc_newsapplication.cpp: newsapplication.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) newsapplication.h -o moc_newsapplication.cpp

moc_resourcemanager.cpp: feedmodel.h \
		resourcemanager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) resourcemanager.h -o moc_resourcemanager.cpp

moc_feedmodel.cpp: feedmodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) feedmodel.h -o moc_feedmodel.cpp

moc_textedit.cpp: textedit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) textedit.h -o moc_textedit.cpp

moc_centerlawidget.cpp: centerlawidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) centerlawidget.h -o moc_centerlawidget.cpp

moc_rssviewwidget.cpp: rssviewwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) rssviewwidget.h -o moc_rssviewwidget.cpp

moc_nodeeditorwidget.cpp: nodeeditorwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) nodeeditorwidget.h -o moc_nodeeditorwidget.cpp

moc_taxonomywidget.cpp: taxonomywidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) taxonomywidget.h -o moc_taxonomywidget.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		images/logo32.png \
		images/mac/editredo.png \
		images/mac/exportpdf.png \
		images/mac/textright.png \
		images/mac/fileprint.png \
		images/mac/editcopy.png \
		images/mac/textunder.png \
		images/mac/editundo.png \
		images/mac/filesave.png \
		images/mac/editcut.png \
		images/mac/fileopen.png \
		images/mac/textcenter.png \
		images/mac/zoomout.png \
		images/mac/textitalic.png \
		images/mac/filenew.png \
		images/mac/textleft.png \
		images/mac/textbold.png \
		images/mac/editpaste.png \
		images/mac/zoomin.png \
		images/mac/textjustify.png \
		images/win/editredo.png \
		images/win/exportpdf.png \
		images/win/textright.png \
		images/win/fileprint.png \
		images/win/editcopy.png \
		images/win/textunder.png \
		images/win/editundo.png \
		images/win/filesave.png \
		images/win/editcut.png \
		images/win/fileopen.png \
		images/win/textcenter.png \
		images/win/zoomout.png \
		images/win/textitalic.png \
		images/win/filenew.png \
		images/win/textleft.png \
		images/win/textbold.png \
		images/win/editpaste.png \
		images/win/zoomin.png \
		images/win/textjustify.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		textedit.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp newsapplication.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		connector.h \
		node.h \
		rssitem.h \
		taxonomyterm.h \
		resourcemanager.h \
		feedmodel.h \
		newsapplication.h \
		centerlawidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

variant.o: qxmlrpc/xmlrpc/variant.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variant.o qxmlrpc/xmlrpc/variant.cpp

serverintrospection.o: qxmlrpc/xmlrpc/serverintrospection.cpp qxmlrpc/xmlrpc/serverintrospection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serverintrospection.o qxmlrpc/xmlrpc/serverintrospection.cpp

server.o: qxmlrpc/xmlrpc/server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o qxmlrpc/xmlrpc/server.cpp

response.o: qxmlrpc/xmlrpc/response.cpp qxmlrpc/xmlrpc/response.h \
		qxmlrpc/xmlrpc/variant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o response.o qxmlrpc/xmlrpc/response.cpp

request.o: qxmlrpc/xmlrpc/request.cpp qxmlrpc/xmlrpc/request.h \
		qxmlrpc/xmlrpc/variant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o request.o qxmlrpc/xmlrpc/request.cpp

client.o: qxmlrpc/xmlrpc/client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o qxmlrpc/xmlrpc/client.cpp

connector.o: connector.cpp connector.h \
		newsapplication.h \
		resourcemanager.h \
		feedmodel.h \
		rssitem.h \
		node.h \
		taxonomyterm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connector.o connector.cpp

newsapplication.o: newsapplication.cpp newsapplication.h \
		resourcemanager.h \
		feedmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newsapplication.o newsapplication.cpp

resourcemanager.o: resourcemanager.cpp resourcemanager.h \
		feedmodel.h \
		node.h \
		file.h \
		rssitem.h \
		taxonomyterm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resourcemanager.o resourcemanager.cpp

feedmodel.o: feedmodel.cpp feedmodel.h \
		resourcemanager.h \
		newsapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o feedmodel.o feedmodel.cpp

textedit.o: textedit.cpp textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textedit.o textedit.cpp

node.o: node.cpp node.h \
		file.h \
		rssitem.h \
		resourcemanager.h \
		feedmodel.h \
		newsapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

file.o: file.cpp file.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file.o file.cpp

rssitem.o: rssitem.cpp rssitem.h \
		taxonomyterm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rssitem.o rssitem.cpp

taxonomyterm.o: taxonomyterm.cpp taxonomyterm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taxonomyterm.o taxonomyterm.cpp

centerlawidget.o: centerlawidget.cpp centerlawidget.h \
		rssviewwidget.h \
		nodeeditorwidget.h \
		node.h \
		rssitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o centerlawidget.o centerlawidget.cpp

rssviewwidget.o: rssviewwidget.cpp rssviewwidget.h \
		rssitem.h \
		taxonomywidget.h \
		resourcemanager.h \
		feedmodel.h \
		newsapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rssviewwidget.o rssviewwidget.cpp

nodeeditorwidget.o: nodeeditorwidget.cpp nodeeditorwidget.h \
		textedit.h \
		node.h \
		rssitem.h \
		resourcemanager.h \
		feedmodel.h \
		newsapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nodeeditorwidget.o nodeeditorwidget.cpp

taxonomywidget.o: taxonomywidget.cpp taxonomywidget.h \
		taxonomyterm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taxonomywidget.o taxonomywidget.cpp

rsslistitemdelegate.o: rsslistitemdelegate.cpp rsslistitemdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rsslistitemdelegate.o rsslistitemdelegate.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_server_private.o: moc_server_private.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server_private.o moc_server_private.cpp

moc_server.o: moc_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server.o moc_server.cpp

moc_client.o: moc_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_client.o moc_client.cpp

moc_connector.o: moc_connector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connector.o moc_connector.cpp

moc_newsapplication.o: moc_newsapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newsapplication.o moc_newsapplication.cpp

moc_resourcemanager.o: moc_resourcemanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resourcemanager.o moc_resourcemanager.cpp

moc_feedmodel.o: moc_feedmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_feedmodel.o moc_feedmodel.cpp

moc_textedit.o: moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textedit.o moc_textedit.cpp

moc_centerlawidget.o: moc_centerlawidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_centerlawidget.o moc_centerlawidget.cpp

moc_rssviewwidget.o: moc_rssviewwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rssviewwidget.o moc_rssviewwidget.cpp

moc_nodeeditorwidget.o: moc_nodeeditorwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nodeeditorwidget.o moc_nodeeditorwidget.cpp

moc_taxonomywidget.o: moc_taxonomywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taxonomywidget.o moc_taxonomywidget.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

